version: "2"

run:
  timeout: 5m

linters:
  enable:
  - errcheck
  - govet
  - staticcheck
  - ineffassign
  - unused
  - misspell
  - goconst
  - gocyclo
  - funlen
  - bodyclose
  - dogsled
  - dupl
  - gochecknoinits
  - goprintffuncname
  - gosec
  - nakedret
  - nolintlint
  - unconvert
  - unparam
  - whitespace
  - lll
  - gocritic
  exclusions:
    generated: lax
    rules:
    - path: _test\.go
      linters:
      - errcheck
      - funlen
    - linters:
      - stylecheck
      text: 'ST1003: should not use underscores in package names'
    - linters:
      - gosec
      text: 'G304: Potential file inclusion via variable'
    - linters:
      - gosec
      text: 'G104: Errors unhandled'
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 120
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
      disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - hugeParam
      - filepathJoin
    gocyclo:
      min-complexity: 25
    lll:
      line-length: 170
    govet:
      settings:
        printf:
          funcs:
          - (github.com/blairham/aws-config/pkg/logutils.Log).Infof
          - (github.com/blairham/aws-config/pkg/logutils.Log).Warnf
          - (github.com/blairham/aws-config/pkg/logutils.Log).Errorf
          - (github.com/blairham/aws-config/pkg/logutils.Log).Fatalf
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: false
    errcheck:
      exclude-functions:
      - (*github.com/bigkevmcd/go-configparser.ConfigParser).AddSection
      - (*github.com/bigkevmcd/go-configparser.ConfigParser).Set
      - (*github.com/bigkevmcd/go-configparser.ConfigParser).RemoveSection
      - (*github.com/bigkevmcd/go-configparser.ConfigParser).SaveWithDelimiter
      - os.Setenv
      - (*os.File).Close
      - (*os/exec.Cmd).Run

formatters:
  enable:
  - gofmt
  - goimports
  exclusions:
    generated: lax
  settings:
    goimports:
      local-prefixes:
      - github.com/blairham/aws-config
