# GoReleaser configuration
version: 2

# Project metadata
project_name: aws-sso-config

before:
  hooks:
  - go mod tidy
  - go generate ./...

builds:
- id: "aws-sso-config"
  main: .
  binary: aws-sso-config
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  # Build flags
  ldflags:
  - -s -w
  - -X main.version={{.Version}}
  - -X main.commit={{.Commit}}
  - -X main.buildTime={{.Date}}
  # Build constraints
  ignore:
  - goos: windows
    goarch: arm64

archives:
- id: "archives"
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  files:
  - README.md
  - LICENSE*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - "^ci:"
    - "^build:"
    - "merge conflict"
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
  groups:
  - title: "New Features"
    regexp: "^.*feat[(\\w)]*:+.*$"
    order: 0
  - title: "Bug Fixes"
    regexp: "^.*fix[(\\w)]*:+.*$"
    order: 1
  - title: "Documentation"
    regexp: "^.*docs[(\\w)]*:+.*$"
    order: 2
  - title: "Other Changes"
    order: 999

release:
  github:
    owner: blairham
    name: aws-sso-config
  name_template: "{{.ProjectName}} v{{.Version}}"
  draft: false
  prerelease: auto

# Homebrew formula (optional - uncomment and configure if desired)
# brews:
#   - repository:
#       owner: blairham
#       name: homebrew-tap
#     directory: Formula
#     homepage: "https://github.com/blairham/aws-sso-config"
#     description: "AWS configuration management tool"
#     license: "MIT"
#     test: |
#       system "#{bin}/aws-sso-config --help"
#     dependencies:
#       - name: git
#     install: |
#       bin.install "aws-sso-config"

# Docker images
dockers:
- image_templates:
  - "ghcr.io/blairham/aws-sso-config:{{ .Version }}-amd64"
  - "ghcr.io/blairham/aws-sso-config:latest-amd64"
  - "aws-sso-config:{{ .Version }}-amd64"
  - "aws-sso-config:latest-amd64"
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  extra_files:
  - "README.md"
  use: buildx
  goos: linux
  goarch: amd64
- image_templates:
  - "ghcr.io/blairham/aws-sso-config:{{ .Version }}-arm64"
  - "ghcr.io/blairham/aws-sso-config:latest-arm64"
  - "aws-sso-config:{{ .Version }}-arm64"
  - "aws-sso-config:latest-arm64"
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  extra_files:
  - "README.md"
  use: buildx
  goos: linux
  goarch: arm64

# Docker manifest for multi-arch images
docker_manifests:
- name_template: "ghcr.io/blairham/aws-sso-config:{{ .Version }}"
  image_templates:
  - "ghcr.io/blairham/aws-sso-config:{{ .Version }}-amd64"
  - "ghcr.io/blairham/aws-sso-config:{{ .Version }}-arm64"
- name_template: "ghcr.io/blairham/aws-sso-config:latest"
  image_templates:
  - "ghcr.io/blairham/aws-sso-config:latest-amd64"
  - "ghcr.io/blairham/aws-sso-config:latest-arm64"
- name_template: "aws-sso-config:{{ .Version }}"
  image_templates:
  - "aws-sso-config:{{ .Version }}-amd64"
  - "aws-sso-config:{{ .Version }}-arm64"
- name_template: "aws-sso-config:latest"
  image_templates:
  - "aws-sso-config:latest-amd64"
  - "aws-sso-config:latest-arm64"

# Go module proxy configuration for better go install support
gomod:
  proxy: true
  env:
  - GOPROXY=https://proxy.golang.org,direct
  - GOSUMDB=sum.golang.org

# Metadata for Go module registry
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
